version: '2'
services:
  nginx:
    image: nginx:1.13.7-alpine
    ports:
      - 3000:80
    volumes:
      - ./docker-config-files/nginx.conf:/etc/nginx/nginx.conf
      - ./docker-config-files/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/smartseller
    links:
      - php-fpm
  php-fpm:
    image: php:7.1-fpm
    volumes:
      - ./:/var/www/smartseller